sudo: required

language: python

dist: xenial
services:
  - docker
  - xvfb

before_install:
  - docker build --build-arg TRAVIS=${TRAVIS} --tag test-xfce-ubuntu:latest .

script:
  - "./travis.sh"

